version: '3.1'
services:
  web:
    image: odoo
    restart: on-failure
    build: .
    depends_on:
      - db
    ports:
      - "8069:8069"
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    env_file:
      - ./.env
